PracticaAula/Models/Employee.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PracticaAula.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre completo es requerido")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "El cargo es requerido")]
        public string Position { get; set; }

        [Required(ErrorMessage = "La fecha de entrada es requerida")]
        public DateTime DateOfAdmission {get; set;}
    }
}

PracticaAula/Models/ErrorViewModel.cs
using System;

namespace PracticaAula.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticaAula/Models/Vacations.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaAula.Models
{
    public class Vacations
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Debe seleccionar una fecha inicio")]
        public DateTime DepartureDate { get; set; }

        [Required(ErrorMessage = "Debe seleccionar una fecha de fin")]
        public DateTime DateOfAdmission { get; set; }

        [Required(ErrorMessage = "Debe seleccionar un empleado")]
        [ForeignKey ("Employee")]
        public int? EmployeeId { get; set; }
        public Employee Employee { get; set; }
    }
}

PracticaAula/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PracticaAula.Data;
using PracticaAula.Models;
using System.Linq;

namespace PracticaAula.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeeController(ApplicationDbContext context)
        {
            _context = context;

        }

        // GET: Employee
        public ActionResult Index()
        {
            var employee = _context.Employee.ToList();
            return View(employee);
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Employee.Add(employee);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            
            return View(employee);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            var employee = _context.Employee.Find(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Employee.Update(employee);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

  
        // POST: Employee/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var employee = _context.Employee.Find(id);

            if (employee == null)
            {
                return NotFound();
            }
            _context.Remove(employee);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PracticaAula/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PracticaAula.Data;
using PracticaAula.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;


namespace PracticaAula.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _applicationDbContext;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext applicationDbContext)
        {
            _logger = logger;
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticaAula/Controllers/VacationsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PracticaAula.Data;
using PracticaAula.Models;
using System.Linq;

namespace PracticaAula.Controllers
{
    public class VacationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VacationsController(ApplicationDbContext context)
        {
            _context = context;

        }
        // GET: VacationsController
        public ActionResult Index()
        {
            var vacations = _context.Vacations.ToList();
            return View(vacations);
        }


        // GET: VacationsController/Create
        public ActionResult Create()
        {
            ViewData["Employee"] = new SelectList(_context.Employee.ToList(), "Id", "FullName");
            return View();
        }

        // POST: VacationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vacations vacations)
        {
            if (ModelState.IsValid)
            {
                _context.Vacations.Add(vacations);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewData["Employee"] = new SelectList(_context.Employee.ToList(), "Id", "FullName");
            return View(vacations);
        }

        // GET: VacationsController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["Employee"] = new SelectList(_context.Employee.ToList(), "Id", "FullName");

            var vacations = _context.Vacations.Find(id);

            if (vacations == null)
            {
                return NotFound();
            }

            return View(vacations);
        }

        // POST: VacationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vacations vacations)
        {
            if (ModelState.IsValid)
            {
                _context.Vacations.Update(vacations);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewData["Employee"] = new SelectList(_context.Employee.ToList(), "Id", "FullName");
            return View(vacations);
        }

     

        // POST: VacationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var vacations = _context.Vacations.Find(id);

            if (vacations == null)
            {
                return NotFound();
            }
            _context.Remove(vacations);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PracticaAula/Views/Employee/Create.cshtml
@model PracticaAula.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Registrar nuevo empleado</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label">Nombre Completo</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label">Cargo</label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfAdmission" class="control-label">Fecha de entrada</label>
                <input asp-for="DateOfAdmission" class="form-control" />
                <span asp-validation-for="DateOfAdmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                 <a class="btn btn-secondary" asp-action="Index">Regresar</a>
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaAula/Views/Employee/Edit.cshtml
@model PracticaAula.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Actualizar empleado</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label">Nombre completo</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label">Cargo</label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfAdmission" class="control-label">Fecha de ingreso</label>
                <input asp-for="DateOfAdmission" class="form-control" />
                <span asp-validation-for="DateOfAdmission" class="text-danger"></span>
            </div>
           <div class="form-group">
                 <a class="btn btn-secondary" asp-action="Index">Regresar</a>
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaAula/Views/Employee/Index.cshtml
@model IEnumerable<PracticaAula.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de empleados</h1>

<p class="text-left">
    <a class="btn btn-primary" asp-action="Create">Nuevo empleado</a>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
               Nombre completo
            </th>
            <th>
               Cargo
            </th>
            <th>
                Fecha de entrada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfAdmission)
            </td>
            <td>
                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                <div class="btn-group">
                    <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                        <button class="btn btn-danger" type="submit" onclick="return functionConfirm(event)">Eliminar</button>
                    </form>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts
  {
    <script type="text/javascript">   
       function functionConfirm(event) 
       {
            swal(
            {
                title: 'Esta seguro de elimar este registro',
                text: "No podrás recuperar este artículo.",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Yes',
                confirmButtonClass: 'btn btn-success'
            }, 
            function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    return true;
                } else {
                    return false;
                }
            });
            return false;
       }
    </script>
}

PracticaAula/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaAula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaAula</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RRHH</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Vacations" asp-action="Index">Vacaciones</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PracticaAula - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>

PracticaAula/Views/Vacations/Create.cshtml
@model PracticaAula.Models.Vacations

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Vacations</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartureDate" class="control-label">Fecha de salida</label>
                <input asp-for="DepartureDate" class="form-control" />
                <span asp-validation-for="DepartureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfAdmission" class="control-label">Fecha de fin</label>
                <input asp-for="DateOfAdmission" class="form-control" />
                <span asp-validation-for="DateOfAdmission" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label">Empleado</label>
                <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.Employee">
                <option value="" default="" selected="">Seleccione un empleado</option>  
                </select>
            </div>
            <div class="form-group">
                 <a class="btn btn-secondary" asp-action="Index">Regresar</a>
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

PracticaAula/Views/Vacations/Edit.cshtml
@model Vacations

@{
    ViewData["Title"] = "Edit";
}

<h1>Actualizar vacaciones </h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DepartureDate" class="control-label">Fecha de Inicio</label>
                <input asp-for="DepartureDate" class="form-control" />
                <span asp-validation-for="DepartureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfAdmission" class="control-label">Fecha de Fin</label>
                <input asp-for="DateOfAdmission" class="form-control" />
                <span asp-validation-for="DateOfAdmission" class="text-danger"></span>
            </div>
             <label asp-for="EmployeeId" class="control-label">Empleado</label>
                <select asp-for="EmployeeId" class ="form-control" asp-items="ViewBag.Employee">
                <option value="" default="" selected="">Seleccione un empleado</option>  
                </select>
              <div class="form-group">
                 <a class="btn btn-secondary" asp-action="Index">Regresar</a>
                <input type="submit" value="Actualizar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PracticaAula/Views/Vacations/Index.cshtml
@model IEnumerable<PracticaAula.Models.Vacations>

@{
    ViewData["Title"] = "Index";
}

<h1>Vacaciones</h1>

<p class="text-left">
    <a class="btn btn-primary" asp-action="Create">Nuevo registro</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
               Fecha de Inicio
            </th>
            <th>
               Fecha de Fin
            </th>
            <th>
                Empleado
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfAdmission)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FullName)
            </td>
            <td>
                 <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                <div class="btn-group">
                    <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                        <button class="btn btn-danger" type="submit" onclick="return functionConfirm(this)">Eliminar</button>
                    </form>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript">
       
        function functionConfirm(event) 
        {
            swal({
                title: 'Esta seguro de borrar este registro?',
                text: "No podrás recuperar este artículo.",
                type: 'warning',
                showCancelButton: true,
                cancelButtonText: 'No',
                cancelButtonClass: 'btn btn-danger',
                showConfirmButton: true,
                confirmButtonText: 'Si',
                confirmButtonClass: 'btn btn-success'
            }, function (isConfirm) {
                if (isConfirm) {
                    $('form').submit();
                    return true;
                } else {
                    return false;
                }
            });
            return false;
        }
    </script>
}